### ISSUE TITLE
java.lang.NoSuchFieldException: TARGET_ZOOM

### ISSUE THREAD

**Issue by ParthChugh** [chaimPaneth/react-native-zoom-bridge#23]
**Logs**
```
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: java.lang.NoSuchFieldException: TARGET_ZOOM
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at java.lang.Class.getField(Class.java:1604)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at i.b.c.n.<clinit>(Unknown Source:23)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at com.zipow.cmmlib.AppContext.<clinit>(Unknown Source:20)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at com.zipow.cmmlib.AppContext.a(Unknown Source:0)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at i.b.a.A.a(Unknown Source:113)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at i.b.a.A.a(Unknown Source:25)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at i.b.a.A.a(Unknown Source:10)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at i.b.a.A.a(Unknown Source:8)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at com.appgoalz.reactnative.a.run(Unknown Source:22)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at android.os.Handler.handleCallback(Handler.java:883)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at android.os.Looper.loop(Looper.java:214)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at java.lang.reflect.Method.invoke(Native Method)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
07-24 00:03:38.524 32617 32617 E ZMBuildConfig: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

Getting this error while building the app, development app works fine 

**build.gradle**
```
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        // # Only using Android Support libraries
        supportLibVersion = "28.0.0"
```

For installing the aar files 
chmod +x ./node_modules/react-native-zoom-bridge/bin/import_prod_sdk.sh
./node_modules/react-native-zoom-bridge/bin/import_prod_sdk.sh

Do we have to do something in android studio?
Thanks In Advance

**Comment by ParthChugh** [comment]
add this line in the ```proguard-rules.pro```, please add this line the documentation as well

```
-keep class us.zoom.** { *; } -keep class us.zipow.** { *; } -keep class com.zipow.** { *; } -keep class org.webrtc.** { *; } -dontwarn us.zoom.** -dontwarn com.zipow.** 
```
